name: Deploy TypeScript Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  frontend-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # GitHub - Install frontend dependencies and build
      - name: Build frontend
        run: |
          npm install  
          cd panel
          npm install
          npm run build
          cd ../sudoku
          npm install
          npm run build
          cd ../connect4
          npm install
          npm run build

      # Start SSH agent with GitHub secret key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Add server to known_hosts to avoid verification errors
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 2222 barryonweb.com >> ~/.ssh/known_hosts
      
      # Nginx config - transfer, enable, check syntax and restart Nginx
      - name: Update Nginx config
        run: |
          ssh -p 2222 barry75@barryonweb.com "mkdir -p /var/www/games/nginx"
          scp -P 2222 gamesjclient.barryonweb.com barry75@barryonweb.com:/var/www/games/nginx/
          ssh -p 2222 barry75@barryonweb.com "
            sudo cp /var/www/games/nginx/gamesjclient.barryonweb.com /etc/nginx/sites-available/ &&
            sudo ln -sf /etc/nginx/sites-available/gamesjclient.barryonweb.com /etc/nginx/sites-enabled/ &&
            sudo nginx -t &&
            sudo systemctl reload nginx"
      

      # Transfer frontend from GitHub Repo to Ubuntu server via SCP
      - name: Deploy frontend via SSH to server
        run: |
          rsync -az -e "ssh -p 2222" panel/dist/ barry75@barryonweb.com:/var/www/games/frontend/panel/
          rsync -az -e "ssh -p 2222" sudoku/dist/ barry75@barryonweb.com:/var/www/games/frontend/sudoku/
          rsync -az -e "ssh -p 2222" connect4/dist/ barry75@barryonweb.com:/var/www/games/frontend/connect4/

